version: "2.1"

services:
  writer:
    image: arm32v7/ubuntu
    volumes:
      - volume_with_label:/data
    command: sh -c 'echo "hello world" >> /data/node-test.txt'

  reader:
    image: arm32v7/ubuntu
    volumes:
      - volume_with_label:/data
    command: sh -c 'sleep 3 && cat /data/node-test.txt'

volumes:
  volume_with_label:
    labels:
      - "label_key=label_val"
